package ExceptionHandling;

public class TryCatch {

	public static void main(String[] args) {
		int num1, num2 = 0;
		try {
			num1=42/num2;
			System.out.println("This will not be executed");
		}catch(ArithmeticException e) {
			System.out.println("Divde by zero");
		}

	}

}
